form_builder/urls.py
from __future__ import unicode_literals

from django.conf.urls import url, include

try:
    from django.views.i18n import JavaScriptCatalog
except:
    from django.views.i18n import javascript_catalog

from . import views
from .constants import FORM_PATH_REGEX


urlpatterns = [
    url(r"^api/", include(("form_builder.api.urls", "form_builder"), namespace="api")),
    url(
        r"^success/{}/(?P<pk>\d+)/$".format(FORM_PATH_REGEX),
        views.SuccessURL.as_view(),
        name="success",
    ),
    url(
        r"^not_available/(?P<pk>\d+)/$",
        views.NotAvailable.as_view(),
        name="not_available",
    ),
    # TODO: Update this view for non-auth users. Currently there is no
    # middleware to solve this auth user.
    url(
        r"^create/{}/$".format(FORM_PATH_REGEX),
        views.FormModelView.as_view(),
        name="create",
    ),
    url(
        r"^resubmit/(?P<pk>\d+)/$",
        views.ResubmitFormModelView.as_view(),
        name="resubmit_view",
    ),
    url(r"^jsi18n/$", JavaScriptCatalog.as_view(), name="javascript-catalog"),
    url(
        r"^submit/(?P<pk>\d+)/export/pdf/$",
        views.SubmitToPDFView.as_view(),
        name="submit_to_pdf",
    ),
    url(
        r"^export/(?P<pk>\d+)/download-attachments/zip/$",
        views.DownloadSubmitAttachmentsView.as_view(),
        name="download_attachments",
    ),
    url(
        r"^cancel_submission_status/$",
        views.cancel_submission_status,
        name="cancel_submission_status",
    ),
    url(r"^print_submit/(?P<pk>\d+)/$", views.print_submission, name="print_submit"),
    url(
        r"^submission_admin/{}/form/(?P<pk>\d+)/detail/$".format(FORM_PATH_REGEX),
        views.SubmissionFormDetailAdmin.as_view(),
        name="submission_form_detail_admin",
    ),
    url(
        r"^export/{}/form/$".format(FORM_PATH_REGEX),
        views.ExportAllView.as_view(),
        name="export_all",
    ),
    url(
        r"^charts/{}/form/$".format(FORM_PATH_REGEX),
        views.ChartsFormView.as_view(),
        name="charts_form",
    ),
    url(
        r"^charts2/{}/form/$".format(FORM_PATH_REGEX),
        views.Charts2FormView.as_view(),
        name="charts2_form",
    ),
]

form_builder/models/form.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from random import randint

from adminsortable.models import Sortable
from autoslug import AutoSlugField
from ckeditor.fields import RichTextField
from django.conf import settings
from django.core.exceptions import ValidationError, MultipleObjectsReturned
from django.apps import apps
from django.contrib.auth import get_user_model

try:
    from django.shortcuts import reverse
except ImportError:
    from django.core.urlresolvers import reverse
from django.core.validators import MaxValueValidator
from django.db import models
from django.db.models import Q

try:
    from django.utils.encoding import python_2_unicode_compatible
except ImportError:
    from django.utils.six import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _
from treebeard.mp_tree import MP_Node

from form_builder import settings as form_settings
from ..utils import get_submitter, reverse_no_i18n
from .field import AbstractFieldFormMixin

User = get_user_model()


class FormFieldQuerySet(models.QuerySet):
    def active(self):
        return self.filter(is_active=True)

    def files(self):
        return self.filter(field_class__in=form_settings.FILE_CLASSES)

    def non_files(self):
        return self.exclude(field_class__in=form_settings.FILE_CLASSES)


class FormFieldManager(models.Manager):
    def get_queryset(self):
        return FormFieldQuerySet(self.model, using=self._db)

    def active(self):
        return self.get_queryset().active()

    def files(self):
        return self.get_queryset().files()

    def non_files(self):
        return self.get_queryset().non_files()


@python_2_unicode_compatible
class AbstractFormField(AbstractFieldFormMixin, Sortable):
    (
        TEXT,
        TEXTAREA,
        RADIO_BUTTON,
        RADIO_BUTTON_INLINE,
        PASSWORD,
        HIDDEN,
        CHECKBOX,
        CHECKBOX_MULTIPLE,
        OPTIONAL_CHOICE,
    ) = (
        "text",
        "textarea",
        "radio",
        "radio_inline",
        "password",
        "hidden",
        "checkbox",
        "checkbox_multiple",
        "optional_choice",
    )

    WIDGET_CHOICES = (
        (TEXT, _("Text")),
        (TEXTAREA, _("Textarea")),
        (RADIO_BUTTON, _("Radio button")),
        (RADIO_BUTTON_INLINE, _("Radio button inline")),
        (PASSWORD, _("Password")),
        (CHECKBOX, _("Checkbox")),
        (CHECKBOX_MULTIPLE, _("Checkbox Multiple")),
        (OPTIONAL_CHOICE, _("Optional Choice")),
        (HIDDEN, _("Hidden")),
    )

    form = models.ForeignKey(
        "form_builder.Form",
        verbose_name=_("form"),
        related_name="fields",
        on_delete=models.CASCADE,
    )
    field = models.ForeignKey(
        "form_builder.Field",
        null=True,
        blank=True,
        related_name="formfield",
        verbose_name=_("field setting"),
        on_delete=models.SET_NULL,
    )
    is_active = models.BooleanField(_("active?"), default=True)
    show_chart = models.BooleanField(_("In Chart?"), default=False)
    is_filter = models.BooleanField(_("As filter"), default=False)
    is_display = models.BooleanField(_("In column"), default=False)
    hidden_by_default = models.BooleanField(_("Hidden"), default=False)
    unique_form_tree = models.BooleanField(
        _("Unique in form tree"),
        default=False,
        help_text=_("Check to make its value shared between all forms"),
    )

    slug = models.CharField(_("Slug"), max_length=64, default="")
    field_class = models.CharField(
        _("Field class"),
        choices=form_settings.FIELD_CLASSES,
        max_length=100,
        default="CharField",
    )
    required = models.BooleanField(_("Required"), default=True)
    label = models.CharField(
        _("Label"), default="", max_length=form_settings.LABEL_MAX_LENGTH,
    )

    objects = FormFieldManager()

    def __str__(self):
        return self.slug

    def clean(self):
        import re

        pattern = re.compile("^([a-z0-9_])*$")
        if not pattern.match(self.slug):
            raise ValidationError(
                _("Please enter a valid name, English small letters, numbers or _")
            )
        super(AbstractFormField, self).clean()

    class Meta:
        verbose_name = _("Form Field")
        verbose_name_plural = _("Form Fields")
        ordering = ("order",)
        abstract = True


class FormQuerySet(models.QuerySet):
    def active(self):
        return self.filter(is_active=True)

    def public(self):
        return self.filter(login_required=False)

    def auth(self):
        return self.filter(login_required=True)


class FormManager(models.Manager):
    def get_queryset(self):
        return FormQuerySet(self.model, using=self._db)

    def active(self):
        return self.get_queryset().active()

    def public(self):
        return self.active().public()

    def auth(self):
        return self.active().auth()

    def get_for_submitter(self, submitter):
        """
        :param submitter: settings.AUTH_USER_MODEL instance
        :return: forms which has the entries submitted by submitter
        """
        return self.filter()

    def get_for_request(self, request):
        return self.active()

    def get_from_path(self, path):
        try:
            return self.get(url_path=path)
        except self.model.DoesNotExist:
            return None


@python_2_unicode_compatible
class AbstractFormType(models.Model):
    name = models.CharField(_("Form Type"), max_length=50)
    users = models.ManyToManyField(User, verbose_name=_("Permitted users"), blank=True)
    groups = models.ManyToManyField(
        "auth.Group", verbose_name=_("Permitted Groups"), blank=True
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _("Form Type")
        verbose_name_plural = _("Form Types")
        abstract = True


@python_2_unicode_compatible
class AbstractForm(MP_Node):
    """
    A form can have fields or no, or it can be used for
    navigational purposes.

    We can have the following cases:

    1. One form with fields
        - the submit method will called from the form directly

    2. One parent form and one or multiple children forms
        - moderated has to be False on all children
    """

    ENTRY_CONDITION = (
        ("single", _("One Time")),
        ("multiple", _("Multiple")),
        ("sequential", _("sequential")),
    )
    entry_condition = models.CharField(
        _("Entry Condition"),
        max_length=50,
        choices=ENTRY_CONDITION,
        default="single",
        null=True,
        blank=True,  # Accepting null is a transient state to be able to import NF DB
        help_text=_("Respected only if login required is enabled"),
    )
    days_next_submit = models.IntegerField(
        default=0, verbose_name=_("Days between submissions")
    )
    is_active = models.BooleanField(_("is active?"), default=True, db_index=True)
    login_required = models.BooleanField(
        _("login required"),
        default=True,
        db_index=True,
        help_text=_("If checked, only registered users can view and fill " "the form."),
    )

    name = models.CharField(_("name"), max_length=50)
    slug = AutoSlugField(
        _("slug"),
        max_length=50,
        unique=True,
        populate_from="name",
        editable=form_settings.EDITABLE_SLUG,
    )
    description = RichTextField(
        _("description"),
        blank=True,
        default="",
        help_text=_("Describe for what is being used this form."),
    )
    resubmission_intro = RichTextField(
        _("Resubmission Introduction"),
        blank=True,
        default="",
        help_text=_("Resubmission Introduction"),
    )
    success_message = RichTextField(
        _("success message"),
        blank=True,
        default="",
        help_text=_("Message showed to the user after submit."),
    )

    notify_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        verbose_name=_("notify Users"),
        blank=True,
        related_name="+",
        help_text=_(
            "Users which shall be notified on form entry submit. "
            "Leave empty for if notifying is not required."
        ),
    )
    notify_groups = models.ManyToManyField(
        "auth.Group", verbose_name=_("Notified Groups"), blank=True
    )
    notify_emails = models.CharField(
        verbose_name=_("Notify Emails"),
        null=True,
        blank=True,
        max_length=200,
        help_text=_(
            "Emails which shall be notified on form entry submit. "
            "Leave empty for if notifying is not required."
            " Add more than one sparated by ;"
        ),
    )
    send_email = models.BooleanField(
        _("send email"),
        default=False,
        help_text=_(
            "If checked, the person entering the form will be sent " "an email"
        ),
    )
    send_email_to_submitter = models.BooleanField(
        _("Send Email To Submitter"),
        default=False,
        help_text=_("If checked, the email template will sent to the submitter"),
    )
    email_from_is_email_field = models.BooleanField(
        _("Email From Is Email Field"),
        default=False,
        help_text=_("If checked, the FROM email will be the user email address"),
    )
    send_files_email = models.BooleanField(
        _("Attach Files to the Email"),
        default=False,
        help_text=_(
            "If checked, the notification email will include files of the form and its parents as attachments"
        ),
    )
    email_field = models.OneToOneField(
        "form_builder.FormField",
        verbose_name=_("email field"),
        null=True,
        blank=True,
        related_name="+",
        on_delete=models.SET_NULL,
        help_text=_(
            "Required only for guest users. Email field where to "
            "notify the submitter is guest"
        ),
    )

form_builder/templates/dashboard/base.html
{% load i18n material_form staticfiles form_builder_utility_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{{ title }}{% endblock %}</title>
    <script type="text/javascript" src='//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js'></script>
    {% include 'material/includes/material_css.html' %}
    <link href="{% static 'css/form_builder/dashboard_custom.css' %}" type="text/css" rel="stylesheet">
    {% block extracss %}{% endblock %}
</head>
<body>
    <ul id="dropdown4" class="dropdown-content">
        {% for form in sidebar_forms %}
        <li class="">
            <a href="{% url 'form_dashboard:submission_form' path=form.slug %}">{{ form.name|truncatechars:'25' }}</a>
        </li>
        {% endfor %}
    </ul>
    <div class="navbar-fixed">
    <nav>
        <div class="nav-wrapper">
            <a href="{% url 'admin:logout' %}" class="right logout"><span class="name center">{% trans 'Logout' %}</span></a>
            {% for language in languages %}
                {% if not language.code == LANGUAGE_CODE %}
                    <a href="{% change_lang language.code %}" class="right logout"><span class="name center">{{ language.name_local }}</span></a>
                {% endif %}
            {% endfor %}
            {% get_language_info_list for LANGUAGES as languages %}
            {% for language in languages %}
                {% if not language.code == LANGUAGE_CODE %}
                    <a href="{% change_lang language.code %}" class="right logout"><span class="name center">{{ language.name_local }}</span></a>
                {% endif %}
            {% endfor %}

        </div>
    </nav>
    </div>
    <div class="content">
        <div class="row">
            <div class="col s12 m12 l12 ">
                <div class="card-panel">
                    {% if messages %}
                        <div class="row" id="alert_box">
                            <div class="col s12 m12">
                                <ul class="messages">
                                    {% for message in messages %}
                                        <div class="card text-{{ message.tags }} darken-1">
                                            <div class="row">
                                                <div class="col s12 m10">
                                                    <div class="card-content white-text">
                                                        <p>{{ message }}</p>
                                                    </div>
                                                </div>
                                                <button type="button" class=" icon_style white-text" aria-label="Close">
                                                    <span aria-hidden="true">×</span>
                                                </button>
                                            </div>
                                        </div>
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>
                    {% endif %}
                    {% block content %}
                    {% endblock %}
                </div>
            </div>
        </div>
    </div>

{% include 'material/includes/material_js.html' %}
<script type="text/javascript">
    $(document).ready(function () {
        $('.icon_style').click(function () {
            $("#alert_box").fadeOut("slow", function () {
            });
        })
    });
</script>
{% block extrajs %}
{% endblock %}
</body>
</html>

form_builder/templates/dashboard/charts.html
{% extends 'dashboard/base.html' %}
{% load material_form i18n staticfiles %}
{% block navbar %}
    <a href="{% url 'form_dashboard:index' %}">{% trans 'Dashboard' %}</a>
    <a class="active">{{ title }}</a>
{% endblock %}
{% block content %}
{% get_current_language_bidi as LANGUAGE_BIDI %}
{% if LANGUAGE_BIDI %}
<style>
    .row .col.s6 {
        float: right !important;
    }
</style>
{% endif %}
<div class="container-fluid">
    <div class="container" style="margin-bottom: 50px;">
        <a href="{{request.path}}?chart_type=pie" class="waves-effect waves-light btn" {% if chart_type == 'pie' %}style="background-color: #fd5f60;"{% endif %}>Pie Chart</a>
        <a href="{{request.path}}?chart_type=bar" class="waves-effect waves-light btn" {% if chart_type == 'bar' %}style="background-color: #fd5f60;"{% endif %}>Bar Chart</a>
    </div>
    <!--<div id="plotly-holder">-->
        <!--<div class="row">-->
            <!--{% for a_graph in graphs %}-->
                <!--<div class="col s6">-->
                    <!--{{ a_graph|safe }}-->
                <!--</div>-->
            <!--{% endfor %}-->


        <!--</div>-->
    <!--</div>-->
    {{ graph|safe }}
    <div id="canvas-holder">
        <div class="row">
            <div class="col s6" style="display: none">
                <canvas id="chart-area" style="display:none"/>
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block extrajs %}
<style></style>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.2.1/Chart.min.js"></script>
<script type="text/javascript">
    var originalData = {{ data }};

    window.chartColors = {
        red: 'rgb(255, 99, 132)',
        orange: 'rgb(255, 159, 64)',
        yellow: 'rgb(255, 205, 86)',
        green: 'rgb(75, 192, 192)',
        blue: 'rgb(54, 162, 235)',
        purple: 'rgb(153, 102, 255)',
        grey: 'rgb(201, 203, 207)'
    };


    function getChartConfig(chartTitle, chartColors, labels, chartData) {
        return {
            type: '{{chart_type}}',
            data: {
                datasets: [{
                    label: chartTitle,
                    data: chartData,
                    backgroundColor: chartColors
                }],
                labels: labels
            },
            options: {
                responsive: true,
                title: {
                display: true,
                text: chartTitle,
                position: 'bottom'
                },
                {% if chart_type == 'bar' %}
                legend: {
                    display: false
                },
                scales: {
                     yAxes: [{
                        ticks: {
                           min: 0,
                        }
                     }]
                }
                {% endif %}
            }
        };
    }


    window.onload = function() {
        var i=1;
        for (var key in originalData) {
            var parentObject = originalData[key];
            var chartTitle = key;
            var chartLabels = [];
            var chartData = [];
            var chartColors = [];
            var chartColorsList = Object.keys(window.chartColors);
            var j=0;
            for (var childKey in parentObject) {
                chartLabels.push(childKey);
                chartData.push(parentObject[childKey]);
                chartColors.push(window.chartColors[chartColorsList[j]]);
                j++;
            }
            var config = getChartConfig(chartTitle, chartColors, chartLabels, chartData);
            var chartAreaId = "chart-area-" + i;
            var chartArea = $("#chart-area").clone().attr("id", chartAreaId).css({"display": "block","float":"left"});
            $('#canvas-holder .row').append('<div class="col s6 graph'+i+'"></div>');
            $('#canvas-holder .row .graph'+i).append(chartArea);
            var ctx = document.getElementById(chartAreaId).getContext("2d");
            window.myPie = new Chart(ctx, config);
            i++;
        }
    };
</script>

{% endblock %}

form_builder/templates/dashboard/charts2.html
{% extends 'dashboard/base.html' %}
{% load material_form i18n staticfiles %}
{% block navbar %}
    <a href="{% url 'form_dashboard:index' %}">{% trans 'Dashboard' %}</a>
    <a class="active">{{ title }}</a>
{% endblock %}
{% block content %}
{% get_current_language_bidi as LANGUAGE_BIDI %}
{% if LANGUAGE_BIDI %}
<style>
    .row .col.s6 {
        float: right !important;
    }
</style>
{% endif %}
<div class="container-fluid">
    <div class="container" style="margin-bottom: 50px;">
        <a href="{{request.path}}?chart_type=pie" class="waves-effect waves-light btn" {% if chart_type == 'pie' %}style="background-color: #fd5f60;"{% endif %}>Pie Chart</a>
        <a href="{{request.path}}?chart_type=bar" class="waves-effect waves-light btn" {% if chart_type == 'bar' %}style="background-color: #fd5f60;"{% endif %}>Bar Chart</a>
    </div>
    <div id="plotly-holder">
        <div class="row">
            {% for a_graph in charts %}
                <div class="col s6">
                    {{ a_graph|safe }}
                </div>
            {% endfor %}


        </div>
    </div>
</div>

{% endblock %}

{% block extrajs %}


{% endblock %}

form_builder/templates/dashboard/children_list.html
{% extends 'dashboard/base.html' %}
{% load material_form i18n staticfiles %}
{% block navbar %}
    <a href="{% url 'form_dashboard:index' %}">{% trans 'Dashboard' %}</a>
    <a class="active">{{ title }}</a>
{% endblock %}
{% block extracss %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/nestable.css' %}">
{% endblock %}
{% block content %}
    <h4 class="header2 center">{{ title }}</h4>
    <div class="row">
        <div class="col s12">
            <a class="btn right"
               href="{% url 'form_dashboard:create_form' %}">{% trans 'Add New Form' %}</a>
        </div>
    </div>
    <div class="dd" id="nestable">
        {% for item, info in children_forms %}
            {% if info.open %}
                <ol class="dd-list">
                <li class="dd-item dd3-item" data-id="{{ item.id }}">
                    {% else %}
                </li>
                <li class="dd-item dd3-item" data-id="{{ item.id }}">
            {% endif %}
        <div class="dd-handle dd3-handle">
        </div>
        <div class="dd3-content">
            <a href="{% url 'rest_form:create'  path=item.url_path %}" target="_blank">
                {{ item|capfirst }}
            </a>
            <a class="right"
               href="{% url 'form_dashboard:edit_form' item.id %}">{% trans 'Edit' %}
                <i class="material-icons tiny">mode_edit</i></a></div>
        {% for close in info.close %}
            </li></ol>
        {% endfor %}
        {% endfor %}
    </div>
{% endblock %}
{% block extrajs %}
    <script src="{% static 'js/jquery.nestable.js' %}" type="text/javascript"></script>
    <script type="text/javascript">
        function getCookie(name) {
            var cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                var cookies = document.cookie.split(';');
                for (var i = 0; i < cookies.length; i++) {
                    var cookie = jQuery.trim(cookies[i]);
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
        var csrftoken = getCookie('csrftoken');
        function csrfSafeMethod(method) {
            // these HTTP methods do not require CSRF protection
            return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
        }
        $.ajaxSetup({
            beforeSend: function (xhr, settings) {
                if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                    xhr.setRequestHeader("X-CSRFToken", csrftoken);
                }
            }
        });
        $(document).ready(function () {
            $('#nestable').nestable({
                dropCallback: function (details) {
                    if (details.destId) {
                        $.post("{% url 'form_dashboard:sortable_form' %}", {
                            'node_id': details.sourceId,
                            'parent_id': details.destId,
                            'next_sibling_id': details.next_sibling,
                            'prev_sibling_id': details.prev_sibling
                        })
                                .done(function (data) {
                                    Materialize.toast(data.message, 5000, 'green white-text');
                                    location.reload(true)
                                })
                                .fail(function (data) {

                                })
                    }
                }
            });
        });
    </script>
{% endblock %}

form_builder/templates/dashboard/delete.html
{% extends 'dashboard/base.html' %}
{% load material_form i18n staticfiles %}
{% block navbar %}
    <a href="{% url 'form_dashboard:index' %}">{% trans 'Dashboard' %}</a>
    <a class="active">{{ title }}</a>
{% endblock %}
{% block content %}
    <form action="" method="POST">
        {% csrf_token %}
        <div class="row">
            <div class="col s12 center red-text">
                <h5>{% trans 'Are you sure you want to delete the selected ' %}"{{ object.name }}"
                    {{ type }} ?</h5>
                {% for children in children_forms %}
                    {% if forloop.first %}
                        <h5>{% trans 'This form has children form that will be deleted: ' %}</h5>
                        <ul class="collection col s6 offset-s3">{% endif %}
                <li class="collection-item">{{ children.name }} {{ type }}</li>
                {% if forloop.last %}</ul>{% endif %}
                {% endfor %}
            </div>

            <div class="col offset-s4 center">
                <a class="btn" onclick="window.history.back(); return false;">{% trans 'Back' %}</a>
            </div>
            <div class="col s2 center">
                <button type="submit" name="_submit" class="btn">{% trans 'Delete' %}</button>
            </div>
        </div>
    </form>
{% endblock %}

form_builder/templates/dashboard/form.html
{% extends 'dashboard/base.html' %}
{% load material_form i18n staticfiles %}
{% block navbar %}
    <a href="{% url 'form_dashboard:index' %}">{% trans 'Dashboard' %}</a>
    <a class="active">{{ title }}</a>
{% endblock %}
{% block content %}
    <h4 class="header2">{{ title }}</h4>
    {% if type == 'form' %}
      <div class="row">
        <div class="col s12">
            <a class="btn right" target="_blank"   href="{% url 'rest_form:create' path=object.slug %}">{% trans 'View on site' %}</a>
        </div>
    </div>
    {% endif %}
    <div class="row">
        <form method="POST">
            {% csrf_token %}
            {% form form=form %}{% endform %}
            {% if formset %}
                <h4 class="header2">{{ inline_title }}</h4>
                {{ formset.management_form }}
                <div class="form_set">
                    {% for f in formset %}
                        {% form form=f %}{% endform %}
                    {% endfor %}
                </div>
                <div class="extra">
                </div>
                <button type="button" class="btn waves-effect waves-light card-panel"
                        id="add-more">{% trans 'Add New' %} {{ formset.form.name }}
                </button>
            {% endif %}
            <div class="col l12 center">
                <button type="submit" name="_submit" class="btn">
                    {% if object %}
                        {% trans 'Update' %}
                    {% else %}
                        {% trans 'Create' %}
                    {% endif %}
                </button>
                <button type="submit" name="_addanother" class="btn" value="addanother">
                        {% if object %}
                            {% trans 'Update and Add another' %}
                        {% else %}
                            {% trans 'Create and Add another' %}
                        {% endif %}
                </button>
                {% if object %}
                    <a class="btn" href="{% url 'form_dashboard:delete' type object.id %}">{% trans 'Delete' %}</a>
                {% endif %}
            </div>

            {% if formset %}
                <script type="text/html" class='no_error' style="display: none">
                    {% form form=formset.empty_form %}{% endform %}
                </script>
            {% endif %}
        </form>
    </div>
{% endblock %}
{% block extrajs %}
    {% if formset %}
        <script type="text/javascript">
            $(document).ready(function () {
                $('#add-more').click(function () {
                    var form_idx = $('#id_form-TOTAL_FORMS').val();
                    $('.extra').append($('.no_error').html().replace(/__prefix__/g, form_idx));
                    $('#id_form-TOTAL_FORMS').val(parseInt(form_idx) + 1);
                    $('select').material_select();
                });
            });
        </script>
    {% endif %}
{% endblock %}

form_builder/templates/dashboard/list.html
{% extends 'dashboard/base.html' %}
{% load material_form i18n staticfiles %}
{% block navbar %}
    <a href="{% url 'form_dashboard:index' %}">{% trans 'Dashboard' %}</a>
    <a class="active">{{ title }}</a>
{% endblock %}
{% block content %}
    <h4 class="header2 center">{{ title }}</h4>
    <div class="row">
        <div class="col s12">
            {% if type == "form" %}
                <a class="btn right"
                   href="{% url 'form_dashboard:create_form' %}">{% trans 'Add New Form' %}</a>
            {% elif type == "field" %}
                <a class="btn right"
                   href="{% url 'form_dashboard:create_field' %}">{% trans 'Add New Field' %}</a>
            {% endif %}
        </div>
    </div>
    {% for obj in object_list %}
        <div class="row obj-list">
            {% if type == "form" %}
                <div class="col s7">
                    <a href="{% url 'rest_form:create'  path=obj.url_path %}"
                       target="_blank">{{ obj.name|capfirst }}</a>
                </div>
                <div class="col s5">
                    <a href="{% url 'form_dashboard:edit_form' obj.id %}">{% trans 'Edit' %}<i
                            class="material-icons tiny">mode_edit</i></a> | <a
                        href="{% url 'form_dashboard:delete' 'form' obj.id %}">{% trans 'Delete' %}<i
                        class="material-icons tiny">delete</i></a>
                </div>
            {% elif type == "field" %}
                <div class="col s7">
                    {{ obj.name|capfirst }}
                </div>
                <div class="col s5">
                    <a href="{% url 'form_dashboard:edit_field' obj.id %}">{% trans 'Edit' %}<i
                            class="material-icons tiny">mode_edit</i></a> | <a
                        href="{% url 'form_dashboard:delete' 'field' obj.id %}">{% trans 'Delete' %}<i
                        class="material-icons tiny">delete</i></a>
                </div>
            {% endif %}
        </div>
        <hr>
    {% empty %}
        <div class="row obj-list">
            <div class="col s12">
                {% trans 'No available' %}
            </div>
        </div>
    {% endfor %}
{% endblock %}